name: PackageManager
version: 1.4.0
date: 2023-02-04
description: |
    Easily download and install GAP packages

authors:
    - name: Michael Young
      url: https://mct25.host.cs.st-andrews.ac.uk/

maintainers:
    - name: Michael Young
      url: https://mct25.host.cs.st-andrews.ac.uk/
    - name: The GAP Team
      url: mailto:support@gap-system.org

GAP: ">= 4.10"

suggested-pkgs:
    - name: "GAPDoc"
      version: ">= 1.6.1"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"
    - name: "curlInterface"
      version: ">= 2.1.0"
      url: "https://gap-packages.github.io/curlInterface/"

www: https://gap-packages.github.io/PackageManager/
readme: README.md
packageinfo: https://gap-packages.github.io/PackageManager/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/PackageManager/releases/download/v1.4.0/PackageManager-1.4.0.tar.gz

abstract: |
    <span class="pkgname">PackageManager</span> is a basic collection of    simple functions for installing and removing    <span class="pkgname">GAP</span> packages, with the eventual aim of    becoming a full pip-style package manager for the    <span class="pkgname">GAP</span> system.

status: deposited
doc-html: doc/chap0_mj.html
doc-pdf: doc/manual.pdf
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>YT23</span>]   <b class='BibAuthor'>Young, M. and GAP Team, T.</b>,
     <i class='BibTitle'>PackageManager, Easily download and install GAP packages,
             Version 1.4.0</i>
     (<span class='BibYear'>2023</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://gap-packages.github.io/PackageManager/">https://gap-packages.github.io/PackageManager/</a></span>.
    </p>
    

bibtex: |
    @misc{ PackageManager1.4.0,
      author =           {Young, M. and GAP Team, T.},
      title =            {{PackageManager},  Easily  download  and  install  GAP
                          packages, {V}ersion 1.4.0},
      month =            {Feb},
      year =             {2023},
      note =             {GAP package},
      howpublished =     {\href {https://gap-packages.github.io/PackageManager/}
                          {\texttt{https://gap-packages.github.io/}\discretionary
                          {}{}{}\texttt{PackageManager/}}},
      printedkey =       {YT23}
    }

