name: PackageManager
version: 1.1
date: 2020-10-14
description: |
    Easily download and install GAP packages

authors:
    - name: Michael Torpey
      url: http://mtorpey.github.io/

maintainers:
    - name: Michael Torpey
      url: http://mtorpey.github.io/

GAP: ">= 4.9"

needed-pkgs:
    - name: "GAPDoc"
      version: ">= 1.6.1"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"

suggested-pkgs:
    - name: "curlInterface"
      version: ">= 2.1.0"
      url: "https://gap-packages.github.io/curlInterface/"

www: https://gap-packages.github.io/PackageManager/
readme: README.md
packageinfo: https://gap-packages.github.io/PackageManager/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/PackageManager/releases/download/v1.1/PackageManager-1.1.tar.gz

abstract: |
    <span class="pkgname">PackageManager</span> is a basic collection of    simple functions for installing and removing    <span class="pkgname">GAP</span> packages, with the eventual aim of    becoming a full pip-style package manager for the    <span class="pkgname">GAP</span> system.

status: deposited
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>Tor20</span>]   <b class='BibAuthor'>Torpey, M.</b>,
     <i class='BibTitle'>PackageManager, Easily download and install GAP packages,
             Version 1.1</i>
     (<span class='BibYear'>2020</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://gap-packages.github.io/PackageManager/">https://gap-packages.github.io/PackageManager/</a></span>.
    </p>
    

bibtex: |
    @misc{ PackageManager1.1,
      author =           {Torpey, M.},
      title =            {{PackageManager},  Easily  download  and  install  GAP
                          packages, {V}ersion 1.1},
      month =            {Oct},
      year =             {2020},
      note =             {GAP package},
      howpublished =     {\href {https://gap-packages.github.io/PackageManager/}
                          {\texttt{https://gap-packages.github.io/}\discretionary
                          {}{}{}\texttt{PackageManager/}}},
      printedkey =       {Tor20}
    }

