name: PackageManager
version: 1.3
date: 2022-08-18
description: |
    Easily download and install GAP packages

authors:
    - name: Michael Young
      url: https://mct25.host.cs.st-andrews.ac.uk/

maintainers:
    - name: Michael Young
      url: https://mct25.host.cs.st-andrews.ac.uk/

GAP: ">= 4.10"

suggested-pkgs:
    - name: "GAPDoc"
      version: ">= 1.6.1"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"
    - name: "curlInterface"
      version: ">= 2.1.0"

www: https://gap-packages.github.io/PackageManager/
readme: README.md
packageinfo: https://gap-packages.github.io/PackageManager/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/PackageManager/releases/download/v1.3/PackageManager-1.3.tar.gz

abstract: |
    <span class="pkgname">PackageManager</span> is a basic collection of    simple functions for installing and removing    <span class="pkgname">GAP</span> packages, with the eventual aim of    becoming a full pip-style package manager for the    <span class="pkgname">GAP</span> system.

status: deposited
doc-html: doc/chap0_mj.html
doc-pdf: doc/manual.pdf
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>You22</span>]   <b class='BibAuthor'>Young, M.</b>,
     <i class='BibTitle'>PackageManager, Easily download and install GAP packages,
             Version 1.3</i>
     (<span class='BibYear'>2022</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://gap-packages.github.io/PackageManager/">https://gap-packages.github.io/PackageManager/</a></span>.
    </p>
    

bibtex: |
    @misc{ PackageManager1.3,
      author =           {Young, M.},
      title =            {{PackageManager},  Easily  download  and  install  GAP
                          packages, {V}ersion 1.3},
      month =            {Aug},
      year =             {2022},
      note =             {GAP package},
      howpublished =     {\href {https://gap-packages.github.io/PackageManager/}
                          {\texttt{https://gap-packages.github.io/}\discretionary
                          {}{}{}\texttt{PackageManager/}}},
      printedkey =       {You22}
    }

