name: CI

# Trigger the workflow on push or pull request
on:
  push:
    branches:
      - master
      - main
  pull_request:
  workflow_dispatch:

# the `concurrency` settings ensure that not too many CI jobs run in parallel
concurrency:
  # group by workflow and ref; the last slightly strange component ensures that for pull
  # requests, we limit to 1 concurrent job, but for the default repository branch we don't
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.ref_name != github.event.repository.default_branch || github.run_number }}
  # Cancel intermediate builds, but only if it is a pull request build.
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  # The CI test job
  test:
    name: ${{ matrix.gap-branch }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        gap-branch:
          - master
          - stable-4.15
          - stable-4.14
          - stable-4.13
          - stable-4.12

    steps:
      - uses: actions/checkout@v5
      - name: 'Install additional dependencies'
        run: |
          sudo apt-get update
          packages=(
            texlive-latex-base
            texlive-latex-recommended
            texlive-latex-extra
            texlive-extra-utils
            texlive-fonts-recommended
            texlive-fonts-extra
            libcurl4-openssl-dev
          )
          sudo apt-get install "${packages[@]}"
      - uses: gap-actions/setup-gap@v2
        with:
          GAP_PKGS_TO_BUILD: "io profiling json curlInterface"
          GAPBRANCH: ${{ matrix.gap-branch }}
      - uses: gap-actions/build-pkg@v1
      - uses: gap-actions/run-pkg-tests@v3
      - uses: gap-actions/run-pkg-tests@v3
        with:
          only-needed: true
      - uses: gap-actions/process-coverage@v2
      - uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
